"""Compact board representation and primitive checker movement."""

from __future__ import annotations

from dataclasses import dataclass, field

from .constants import BLACK, CHECKERS_PER_PLAYER, NUM_POINTS, WHITE, Player
from .moves import Move


@dataclass(slots=True)
class Board:
    """A board whose signed point counts encode owner and checker count.

    Positive counts are White checkers and negative counts are Black checkers.
    Point indices are physical indices 0..23. White moves upward and Black
    moves downward.
    """

    points: list[int] = field(default_factory=lambda: [0] * NUM_POINTS)
    bar: dict[Player, int] = field(default_factory=lambda: {WHITE: 0, BLACK: 0})
    off: dict[Player, int] = field(default_factory=lambda: {WHITE: 0, BLACK: 0})

    @classmethod
    def initial(cls) -> Board:
        points = [0] * NUM_POINTS
        points[0] = 2
        points[11] = 5
        points[16] = 3
        points[18] = 5
        points[23] = -2
        points[12] = -5
        points[7] = -3
        points[5] = -5
        return cls(points=points)

    @classmethod
    def empty(cls) -> Board:
        return cls()

    def copy(self) -> Board:
        return Board(self.points.copy(), self.bar.copy(), self.off.copy())

    def checker_count(self, player: Player) -> int:
        on_board = sum(abs(value) for value in self.points if value * int(player) > 0)
        return on_board + self.bar[player] + self.off[player]

    def validate(self) -> None:
        if len(self.points) != NUM_POINTS:
            raise ValueError("A board must contain exactly 24 points")
        if self.checker_count(WHITE) != CHECKERS_PER_PLAYER:
            raise ValueError("White must have exactly 15 checkers")
        if self.checker_count(BLACK) != CHECKERS_PER_PLAYER:
            raise ValueError("Black must have exactly 15 checkers")
        if any(count < 0 for count in (*self.bar.values(), *self.off.values())):
            raise ValueError("Bar and borne-off counts cannot be negative")

    def apply_move(self, move: Move, player: Player) -> None:
        """Apply a rule-checked move generated by ``rules``.

        This primitive deliberately does not decide legality; keeping that logic
        in one generator prevents the GUI and agents from duplicating rules.
        """

        from .constants import BAR, OFF

        sign = int(player)
        if move.destination != OFF:
            if not 0 <= move.destination < NUM_POINTS:
                raise ValueError("Destination is outside the board")
            if self.points[move.destination] * sign <= -2:
                raise ValueError("Cannot move to a blocked point")
        if move.source == BAR:
            if self.bar[player] <= 0:
                raise ValueError("No checker is available on the bar")
            self.bar[player] -= 1
        else:
            if (
                not 0 <= move.source < NUM_POINTS
                or self.points[move.source] * sign <= 0
            ):
                raise ValueError("Source does not contain a checker for this player")
            self.points[move.source] -= sign

        if move.destination == OFF:
            self.off[player] += 1
            return

        destination_count = self.points[move.destination]
        if destination_count * sign == -1:
            self.points[move.destination] = 0
            self.bar[Player(-sign)] += 1
        self.points[move.destination] += sign

    def pip_count(self, player: Player) -> int:
        bar_pips = self.bar[player] * 25
        if player == WHITE:
            board_pips = sum(
                (24 - index) * value
                for index, value in enumerate(self.points)
                if value > 0
            )
        else:
            board_pips = sum(
                (index + 1) * -value
                for index, value in enumerate(self.points)
                if value < 0
            )
        return board_pips + bar_pips
